package com.vida.app.ui.theme

import androidx.compose.ui.graphics.Color

// Fallback light palette (used on SDK 26-30 where dynamic color is unavailable)
val FallbackLightPrimary = Color(0xFF4A6741)
val FallbackLightOnPrimary = Color(0xFFFFFFFF)
val FallbackLightPrimaryContainer = Color(0xFFCCEFC0)
val FallbackLightOnPrimaryContainer = Color(0xFF092100)
val FallbackLightSecondary = Color(0xFF55624C)
val FallbackLightOnSecondary = Color(0xFFFFFFFF)
val FallbackLightSecondaryContainer = Color(0xFFD9E7CB)
val FallbackLightOnSecondaryContainer = Color(0xFF131F0E)
val FallbackLightTertiary = Color(0xFF386666)
val FallbackLightOnTertiary = Color(0xFFFFFFFF)
val FallbackLightTertiaryContainer = Color(0xFFBCEBEB)
val FallbackLightOnTertiaryContainer = Color(0xFF002020)
val FallbackLightError = Color(0xFFBA1A1A)
val FallbackLightOnError = Color(0xFFFFFFFF)
val FallbackLightErrorContainer = Color(0xFFFFDAD6)
val FallbackLightOnErrorContainer = Color(0xFF410002)
val FallbackLightBackground = Color(0xFFFBFDF6)
val FallbackLightOnBackground = Color(0xFF1A1C18)
val FallbackLightSurface = Color(0xFFFBFDF6)
val FallbackLightOnSurface = Color(0xFF1A1C18)
val FallbackLightSurfaceVariant = Color(0xFFE0E4D6)
val FallbackLightOnSurfaceVariant = Color(0xFF44483D)
val FallbackLightOutline = Color(0xFF74796C)

// Fallback dark palette
val FallbackDarkPrimary = Color(0xFFB0D3A5)
val FallbackDarkOnPrimary = Color(0xFF1B3714)
val FallbackDarkPrimaryContainer = Color(0xFF324F2A)
val FallbackDarkOnPrimaryContainer = Color(0xFFCCEFC0)
val FallbackDarkSecondary = Color(0xFFBDCBB0)
val FallbackDarkOnSecondary = Color(0xFF273420)
val FallbackDarkSecondaryContainer = Color(0xFF3D4B35)
val FallbackDarkOnSecondaryContainer = Color(0xFFD9E7CB)
val FallbackDarkTertiary = Color(0xFFA0CFCF)
val FallbackDarkOnTertiary = Color(0xFF003737)
val FallbackDarkTertiaryContainer = Color(0xFF1E4E4E)
val FallbackDarkOnTertiaryContainer = Color(0xFFBCEBEB)
val FallbackDarkError = Color(0xFFFFB4AB)
val FallbackDarkOnError = Color(0xFF690005)
val FallbackDarkErrorContainer = Color(0xFF93000A)
val FallbackDarkOnErrorContainer = Color(0xFFFFDAD6)
val FallbackDarkBackground = Color(0xFF1A1C18)
val FallbackDarkOnBackground = Color(0xFFE3E3DC)
val FallbackDarkSurface = Color(0xFF1A1C18)
val FallbackDarkOnSurface = Color(0xFFE3E3DC)
val FallbackDarkSurfaceVariant = Color(0xFF44483D)
val FallbackDarkOnSurfaceVariant = Color(0xFFC4C8BB)
val FallbackDarkOutline = Color(0xFF8E9286)